/*
 * generated by Xtext 2.12.0
 */
package uk.ac.lancaster.scc.turtles.clouseau


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ClouseauStandaloneSetup extends ClouseauStandaloneSetupGenerated {

	def static void doSetup() {
		new ClouseauStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
