/*
 * generated by Xtext 2.12.0
 */
package uk.ac.lancaster.scc.turtles.clouseau


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ClouseauRuntimeModule extends AbstractClouseauRuntimeModule {
}
