/*
 * generated by Xtext 2.12.0
 */
package uk.ac.lancaster.scc.turtles.clouseau.ide


/**
 * Use this class to register ide components.
 */
class ClouseauIdeModule extends AbstractClouseauIdeModule {
}
