/*
 * generated by Xtext 2.12.0
 */
package uk.ac.lancaster.scc.turtles.clouseau.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ClouseauInjectorProvider)
class ClouseauParsingTest {
	
	@Test
	def void loadModel() {

	}
}
